### ISSUE TITLE
The listen command

### ISSUE THREAD

**Issue by dairlair** [dairlair/sentimentd#21]
As a User, I want to run `sentimentd` as a daemon, which consumes messages from NATS Streaming channel, analyzes them and pushes results to another queue. This feature will allow building an event-driven architecture.

The configuration may look like this:

```yaml
# The configuration presented bellow runs sentimentd as a daemon which subscribed to messages
# from NATS Streaming server, analyses them though brain "skynet" and pushes the results to the NATS Streaming back.
listen:
  in:
    url: "nats://127.0.0.1:4222"
    clusterId: "test-cluster"
    clientId: "sentimentd"
    channel: "TweetSaved"
  out:
    url: "nats://127.0.0.1:4222"
    clusterId: "test-cluster"
    clientId: "sentimentd"
    channel: "TweetAnalysed"
  brain: "skynet"
```
