### ISSUE TITLE
Log Level Control

### ISSUE THREAD

**Issue by dairlair** [dairlair/sentimentd#24]
As a DevOps, I want to configure the log level and format for application through config file or environment variables so that let me be happy.

**Comment by dairlair** [comment]
Now you can do it with config section:

```yaml
log:
  # Available values: panic, fatal, error, warn, warning, info, debug, trace
  # If omitted or empty then 'warn' level will be used
  level: "info"
  # Available values: json, text
  format: "json"
```

Or with environment variables:
```
LOG_LEVEL="info" \
LOG_FORMAT="json" \
sentimentd brain ls
```
